# Generated by Django 5.1 on 2025-12-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0003_alter_articlemodel_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'CoreAPI'), ('model__in', ['vehiculemodel', 'warehousemodel'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
