# Generated by Django 5.1 on 2025-12-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0004_alter_articlemodel_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='object_id',
            new_name='site_id',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='content_type',
            new_name='site_type',
        ),
    ]
