# Generated by Django 5.1 on 2025-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0005_rename_object_id_articlemodel_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='image',
            field=models.ImageField(blank=True, default='default_driver.png', null=True, upload_to='DriverImages/'),
        ),
    ]
