# Generated by Django 5.2.7 on 2026-01-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0006_drivermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculemodel',
            name='available',
            field=models.CharField(choices=[('Free', 'Free'), ('Used', 'Used')], default='Free', max_length=5),
        ),
    ]
