# Generated by Django 5.1 on 2026-01-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0007_vehiculemodel_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.CharField(max_length=8)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=1)),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CoreAPI.vehiculemodel')),
            ],
        ),
    ]
