# Generated by Django 5.1 on 2026-01-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0008_missionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionmodel',
            old_name='truck_id',
            new_name='truck',
        ),
    ]
