# Generated by Django 5.1 on 2026-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0009_rename_truck_id_missionmodel_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionmodel',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1),
        ),
    ]
